name: exmaple_app

services:
  redis:
    restart: no
    image: redis:7
    ports:
      - 127.0.0.1:${REDIS_PORT}:6379

  db:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    restart: no
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 127.0.0.1:${POSTGRES_PORT}:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

  # Не требуется для работы, нужен только для наглядного просмотра содержимого Redis
  redisinsight:
    image: redis/redisinsight:latest
    restart: no
    ports:
      - 127.0.0.1:5540:5540

  # Не требуется для работы, нужен только для наглядного просмотра содержимого Postgres
  adminer:
    image: adminer:latest
    restart: no
    ports:
      - 127.0.0.1:8084:8080

volumes:
  pg_data:
